on: release
name: mediasummon release workflow
jobs:
  githubOfficialAction:
    name: github official action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: docker action
      uses: docker://node:6
      with:
        args: node --version
    - name: build binaries
      uses: ericflo/actions/golang-build@master
      with:
        args: "windows/amd64 windows/386 linux/amd64 linux/386 linux/arm/5 linux/arm/6 linux/arm/7 darwin/amd64 darwin/386"
    - name: upload windows/amd64 binary
      uses: JasonEtco/upload-to-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: /github/workspace/.release/mediasummon_windows_amd64 application/octet-stream
    - name: upload windows/386 binary
      uses: JasonEtco/upload-to-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: /github/workspace/.release/mediasummon_windows_386 application/octet-stream
    - name: upload linux/amd64 binary
      uses: JasonEtco/upload-to-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: /github/workspace/.release/mediasummon_linux_amd64 application/octet-stream
    - name: upload linux/386 binary
      uses: JasonEtco/upload-to-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: /github/workspace/.release/mediasummon_linux_386 application/octet-stream
    - name: upload darwin/amd64 binary
      uses: JasonEtco/upload-to-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: /github/workspace/.release/mediasummon_darwin_amd64 application/octet-stream
    - name: upload darwin/386 binary
      uses: JasonEtco/upload-to-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: /github/workspace/.release/mediasummon_darwin_386 application/octet-stream
    - name: upload linux/arm/5 binary
      uses: JasonEtco/upload-to-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: /github/workspace/.release/mediasummon_linux_arm5 application/octet-stream
    - name: upload linux/arm/6 binary
      uses: JasonEtco/upload-to-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: /github/workspace/.release/mediasummon_linux_arm6 application/octet-stream
    - name: upload linux/arm/7 binary
      uses: JasonEtco/upload-to-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: /github/workspace/.release/mediasummon_linux_arm7 application/octet-stream
